export const MapPlatFormName = {
  Platform: '平台名称',
  DepositFund: '资金存款',
  Operator: '运营公司',
  OnlineTime: '上线时间',
  InterestRate: '利息水平',
  InvestmentHorizon: '投资期限',
  RegisteredFund: '注册资金',
  GuaranteeCompany: '担保公司',
  Withdraw: '提现到账',
  PhoneNumber: '客服电话',
  BackgroundPedestal: '平台背景',
  BackgroundFinancing: '融资背景',
  Address: '公司地址',
}
